#!/bin/bash

# You should run this command from the project root directory.

# To enable python to discover tests, test files should be named
# test*.py and be located in a directory that includes an __init__.py
# file.

set -ex
# In the above line, "set -x" causes this script to exit as soon as
# any line fails. "set -e" causes each line of this script to be
# printed (with a + in front) before it is executed, so if a step
# fails, you can see from the travis log what command failed.


for j in {1..3}
do
    mpiexec -n $j python -m unittest -v
done
