#!/bin/bash

# You should run this command from the project root directory.

# To enable python to discover tests, test files should be named
# test*.py and be located in a directory that includes an __init__.py
# file.

set -ex
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

for j in {1..3}
do
    mpiexec -n $j python -m unittest -v -s ${DIR}/tests
done
