#!/bin/bash

# You should run this command from the project root directory.

# To enable python to discover tests, test files should be named
# test*.py and be located in a directory that includes an __init__.py
# file.

set -ex
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

echo "Checking if we are in the Github Actions CI: ${GITHUB_ACTIONS:+--oversubscribe}"

for j in {1..3}
do
    # In the next line, ${GITHUB_ACTIONS:+--oversubscribe} evaluates to --oversubscribe if the environment variable GITHUB_ACTIONS is set, and evaluates to nothing if the variable is not set.
    mpiexec ${GITHUB_ACTIONS:+--oversubscribe} -n $j python -m unittest discover -v -s ${DIR}/tests
done
