package:
  name: vmec
  version: 0.0.5

source:
  path: ..
  # patches:
  #   - no_clang.patch

build:
  include_recipe: False
  skip: True  # [win or py<37]
  number: 0

  script:
    - cp {{ SRC_DIR }}/cmake/machines/conda.json {{ SRC_DIR }}/cmake_config_file.json
    - {{ PYTHON }} -m pip install --no-deps --ignore-installed . -v
  run_exports:
    - f90wrap
    - hdf5
    - netcdf4
    - netcdf-fortran
    - scalapack   
    - mkl

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - cmake
    - ninja
    - f90wrap
    - hdf5
    - netcdf4
    - netcdf-fortran
    - python {{ python }}
    - scikit-build
    - numpy {{ numpy }}

  host:
    - python
    - pip
    - numpy 
    - f90wrap
    - ninja
    - {{ mpi }}
    - scikit-build
    - hdf5
    - netcdf4
    - netcdf-fortran
    - scalapack
    - libblas
    - liblapack

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - {{ mpi }}
    - f90wrap
    - hdf5
    - netcdf4
    - netcdf-fortran
    - scalapack

test:
  commands:
    - python -c "import vmec; print('success')"

about:
  home: https://github.com/hiddensymmetries/vmec2000
  summary: Python extension for VMEC
  license: MIT
  license_file: LICENSE
  doc_url: https://hiddensymmetries.github.io/VMEC2000/
  dev_url: https://github.com/hiddensymmetries/vmec2000

extra:
  recipe-maintainers:
    - mbkumar
    - landreman
